In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/rainfall/201807_202306

Mounted at /content/drive
/content/drive/MyDrive/rainfall/201807_202306

In [ ]:
import numpy as np
import os
import pandas as pd
from datetime import datetime, timedelta

In [ ]:
temp=pd.read_csv('A_TEMP_223132_1141704.csv',skiprows=3,usecols=[0,2])
temp=temp.groupby(['Time']).mean()
temp=temp.reset_index()
temp['Time'] = pd.to_datetime(temp.Time, format = '%Y/%m/%d %H:%M:%S')
temp['Date']=temp['Time'].dt.strftime('%Y-%m-%d')

In [ ]:
max=temp.groupby(['Date']).max()
min=temp.groupby(['Date']).min()
max,min

In [ ]:
climate=pd.concat([max['Degree Celsius'],min['Degree Celsius']],axis=1)
climate=climate.reset_index()
climate.columns =['Date','max','min']

In [ ]:
df = climate
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)
start_date = '2018-07-01'
end_date = '2023-06-30'
date_range = pd.date_range(start_date, end_date, freq='D')
new_df = pd.DataFrame(index=date_range)
df = df.interpolate(method='linear')
missing_values = new_df.loc[~new_df.index.isin(df.index)]
print(missing_values)

In [ ]:
df.loc['2023-01-16', 'max'] = np.nan
df.loc['2023-01-16', 'min'] = np.nan
df.loc['2023-01-17', 'max'] = np.nan
df.loc['2023-01-17', 'min'] = np.nan
df = df.sort_index(ascending=True)
df = df.interpolate(method='linear')
missing_values = new_df.loc[~new_df.index.isin(df.index)]
print(missing_values)

In [ ]:
climate = df
climate = climate.reset_index()
climate['year']=pd.DatetimeIndex(climate['Date']).year
climate['month']=pd.DatetimeIndex(climate['Date']).month
climate['day']=pd.DatetimeIndex(climate['Date']).day
climate['station']='KP_AWS'
climate['eva']='*'
climate

In [ ]:
wind = pd.read_csv('A_WIND_223132_1141704.csv',skiprows=3,usecols=[0,2])
wind = wind.groupby(['Time']).mean(numeric_only=True)
wind = wind.reset_index()
wind['Time'] = pd.to_datetime(wind.Time, format = '%Y/%m/%d %H:%M:%S')
wind['Date'] = wind['Time'].dt.strftime('%Y-%m-%d')
wind['km/h'] = wind['m/s']*60*60/1000
wind_average = wind.groupby(['Date']).mean(numeric_only=True)
wind_average = wind_average.reset_index()
wind_average

In [ ]:
climate=pd.concat([climate,wind_average['km/h']],axis=1)
climate

           Date   max   min  year  month  day station eva       km/h
0    2018-07-01  32.8  28.3  2018      7    1  KP_AWS   *   8.817223
1    2018-07-02  30.8  25.6  2018      7    2  KP_AWS   *   8.382499
2    2018-07-03  30.1  28.0  2018      7    3  KP_AWS   *   9.413612
3    2018-07-04  32.2  27.9  2018      7    4  KP_AWS   *  10.937779
4    2018-07-05  30.5  28.5  2018      7    5  KP_AWS   *   9.130833
...         ...   ...   ...   ...    ...  ...     ...  ..        ...
1821 2023-06-26  31.2  26.0  2023      6   26  KP_AWS   *   8.391307
1822 2023-06-27  32.1  27.4  2023      6   27  KP_AWS   *  10.833331
1823 2023-06-28  30.4  26.2  2023      6   28  KP_AWS   *   8.833334
1824 2023-06-29  32.8  26.8  2023      6   29  KP_AWS   *   6.541668
1825 2023-06-30  31.7  26.2  2023      6   30  KP_AWS   *   7.541667

[1826 rows x 9 columns]

In [ ]:
climate.columns

Index(['Date', 'max', 'min', 'year', 'month', 'day', 'station', 'eva', 'km/h'], dtype='object')

In [ ]:
climate=climate.reindex(columns=['station', 'year', 'month', 'day','max', 'min', 'eva', 'km/h'])
climate

     station  year  month  day   max   min eva       km/h
0     KP_AWS  2018      7    1  32.8  28.3   *   8.817223
1     KP_AWS  2018      7    2  30.8  25.6   *   8.382499
2     KP_AWS  2018      7    3  30.1  28.0   *   9.413612
3     KP_AWS  2018      7    4  32.2  27.9   *  10.937779
4     KP_AWS  2018      7    5  30.5  28.5   *   9.130833
...      ...   ...    ...  ...   ...   ...  ..        ...
1821  KP_AWS  2023      6   26  31.2  26.0   *   8.391307
1822  KP_AWS  2023      6   27  32.1  27.4   *  10.833331
1823  KP_AWS  2023      6   28  30.4  26.2   *   8.833334
1824  KP_AWS  2023      6   29  32.8  26.8   *   6.541668
1825  KP_AWS  2023      6   30  31.7  26.2   *   7.541667

[1826 rows x 8 columns]

In [ ]:
climate=climate.round(1)
climate

     station  year  month  day   max   min eva  km/h
0     KP_AWS  2018      7    1  32.8  28.3   *   8.8
1     KP_AWS  2018      7    2  30.8  25.6   *   8.4
2     KP_AWS  2018      7    3  30.1  28.0   *   9.4
3     KP_AWS  2018      7    4  32.2  27.9   *  10.9
4     KP_AWS  2018      7    5  30.5  28.5   *   9.1
...      ...   ...    ...  ...   ...   ...  ..   ...
1821  KP_AWS  2023      6   26  31.2  26.0   *   8.4
1822  KP_AWS  2023      6   27  32.1  27.4   *  10.8
1823  KP_AWS  2023      6   28  30.4  26.2   *   8.8
1824  KP_AWS  2023      6   29  32.8  26.8   *   6.5
1825  KP_AWS  2023      6   30  31.7  26.2   *   7.5

[1826 rows x 8 columns]

In [ ]:
climate.to_csv('climate2018_2023.dat',sep='\t',header=False, index=False)